### ISSUE TITLE
Make application responsive 

### ISSUE THREAD

**Issue by RishabhJain0721** [RishabhJain0721/Brain-Box#1]

**Comment by Muz4mmil** [comment]
You have used TailwindCSS for styling.
Moving the Subject selection pane to a Nav menu on mobile devices will be good UX idea.
I can make it fully responsive easily. But I need few days for it.
Kindly assign this to me under Hacktoberfest.

**Comment by RishabhJain0721** [comment]
Alright go ahead

**Comment by Muz4mmil** [comment]
> Alright go ahead

Is it Okay na if I Move the Subjects pane to Navigation Menu in mobiles???

**Comment by RishabhJain0721** [comment]
Yes it is fine✌️

**Comment by Muz4mmil** [comment]
> Yes it is fine✌️

Hi @RishabhJain0721 ,
I m trying to add styling on dashboard page but It requires an account, i signed up and tried to login but it says "Error fetching student data".
Can you provide  demo or test credentials so that i can continue to work on responsiveness?

**Comment by RishabhJain0721** [comment]
Hi @Muz4mmil 
Sorry for responding late. Was at a family function.
After creating a new account and logging in, "Add Subject" button should be visible ideally(still working for me).
It still you are facing some problems, here are the test credentials :
email : yagami@gmail.com
pass : 123456

**Comment by Muz4mmil** [comment]
@RishabhJain0721 Hi, 
Actually, sorry from my side too because i won't be able to work on this for next couple of days. I will surely try to complete it after Monday.
And thanks for sharing credentials.
Lets hope it gets counted to hacktoberfest

**Comment by RishabhJain0721** [comment]
@Muz4mmil No issues. Wishing you luck 👍🏻

**Comment by Muz4mmil** [comment]
@RishabhJain0721 Should I make PR directly to main branch??
