### ISSUE TITLE
UI Improvement Of Login, Signup Page

### ISSUE THREAD

**Issue by psykat1116** [RishabhJain0721/Brain-Box#14]
I Want to Improve the UI of the home page with the Login and signup Page. Please assign me for this under JWOC 2024.

**Comment by RishabhJain0721** [comment]
@psykat1116 Go ahead.

Add some loader animation when a user clicks the login/signup button.
If some error occurs while login/signup, show it in a nice and clean dialog box.

**Comment by Hacxmr** [comment]
Hey! @RishabhJain0721  I'm interested in working on UI enhancement. Kindly assign me this under JWOC'24

**Comment by RishabhJain0721** [comment]
@psykat1116 Raise a PR by today 2 pm or I will have to assign it to @Hacxmr

**Comment by psykat1116** [comment]
I am currently busy on another project please give it to someone else.

**Comment by RishabhJain0721** [comment]
@Hacxmr Please go ahead.

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by Hacxmr** [comment]
@vermaanurag1532 I'm working on this
