### ISSUE TITLE
Add to-do list feature for students on website

### ISSUE THREAD

**Issue by KhushiAgarwal22** [RishabhJain0721/Brain-Box#15]
I think its great to add to-do feature so that students can have a list of subjects they have to do and keep a check on their progress of what all subjects they have studied and what all  they still have left.

Please assign me it under JWOC ' 24.
@RishabhJain0721

**Comment by KhushiAgarwal22** [comment]
Please assign me under JWOC'24
@RishabhJain0721

**Comment by RishabhJain0721** [comment]
@KhushiAgarwal22 Alright please go on
