### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by psykat1116** [RishabhJain0721/Brain-Box#5]
I Want to Improve the UI of the home page with the Login and signup Page. Please assign me for this under **JWOC 2024**.

**Comment by MaruthiSingh** [comment]
I would like to work on that issue under JWOC

**Comment by RishabhJain0721** [comment]
@psykat1116 Go ahead. 

1. Add some loader animation when a user clicks the login/signup button. 
2. If some error occurs while login/signup, show it in a nice and clean dialog box.

**Comment by RishabhJain0721** [comment]
Sorry, the issue was raised before 15th Jan so it is not valid.
