### ISSUE TITLE
Add: Dark mode/ Light mode switch 

### ISSUE THREAD

**Issue by AaadityaG** [RishabhJain0721/Brain-Box#6]
Please allow me to work on it under jwoc tag!

**Comment by RishabhJain0721** [comment]
Alright @AaadityaG go ahead

**Comment by RishabhJain0721** [comment]
@AaadityaG Are you facing any issues while setting up locally?

**Comment by AaadityaG** [comment]
@RishabhJain0721 I will raise a pr by tommorow EOD, is that ok? and sorry for late replying!

**Comment by RishabhJain0721** [comment]
@AaadityaG  That's fine.

**Comment by RishabhJain0721** [comment]
@AaadityaG Are you still doing it?

**Comment by AaadityaG** [comment]
Yes, sry for not keeping a promise..

**Comment by AaadityaG** [comment]
I will raise pr today..

**Comment by RishabhJain0721** [comment]
Alright

**Comment by prakharsingh-74** [comment]
@RishabhJain0721 I would like to work on this issue under JWOC please assign it to me

**Comment by RishabhJain0721** [comment]
> @RishabhJain0721 I would like to work on this issue under JWOC please assign it to me

Assigned.

**Comment by prakharsingh-74** [comment]
i have unassigned myself because i'm not available to do this project due to my exams. When i'm available you have not assigned me.

**Comment by KartikSaxena19** [comment]
you can assign this task to me

**Comment by RishabhJain0721** [comment]
Sorry, this project is inactive now. I can assign you if you want to for contribution practice. Do you want me to assign?

**Comment by KartikSaxena19** [comment]
> Sorry, this project is inactive now. I can assign you if you want to for contribution practice. Do you want me to assign?

no sir currently i'm working on another issue
btw i'm also from iet lucknow CSE(SF)'27

**Comment by RishabhJain0721** [comment]
Alright, all the best for your contributions 👍🏻

**Comment by KartikSaxena19** [comment]
> Alright, all the best for your contributions 👍🏻

sir can i contact you later like for future use(for contributions) if so how can i contact you

**Comment by RishabhJain0721** [comment]
yeah sure. mail/linkedin etc.
