### ISSUE TITLE
Links adding error

### ISSUE THREAD

**Issue by RishabhJain0721** [RishabhJain0721/Brain-Box#9]
When I add a link in under a chapter after deleting some link from the same chapter, error arises.
Fix Required.

![Screenshot 2024-01-17 003101](https://github.com/RishabhJain0721/Brain-Box/assets/107767172/3a7d1d75-25b1-483f-8533-bdb505c1f4ff)

**Comment by n0n3br** [comment]
can you assing this to me @RishabhJain0721 ?

**Comment by MaruthiSingh** [comment]
I would like to work on that issue under JWOC

**Comment by RishabhJain0721** [comment]
@MaruthiSingh Go ahead please.
@n0n3br Sorry can't assign two issues simultaneously.
